import type { Metadata } from "next";
import "../styles/globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "./providers/providers";
import NavBarUi from "@/components/NavBarUi";

export const metadata: Metadata = {
  title: "JoyProfits",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* <Navbar /> */}
          <NavBarUi />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
